# Generated by Django 3.0.4 on 2020-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("matches", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("goals", models.PositiveIntegerField(default=0)),
                ("goals_conceded", models.PositiveIntegerField(default=0)),
            ],
            options={"verbose_name": "team", "verbose_name_plural": "teams",},
        ),
    ]
